version: 2
updates:
  # Check for updates to GitHub Actions every weekday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

# scala updates are handed by the Scala Steward action.
# https://github.com/target/data-validator/blob/master/.github/workflows/scala-steward.yaml
