name: Release

on:
  push:
    tags:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    steps:
      - uses: ./.github/actions/ci@v1
      # uses sbt-github-packages, see build.sbt
      - run: bin/sbt publish

