name: Release

on:
  push:
    tags: "[1-9]+.[0-9]+.[0-9]+"
    branches: master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: target/data-validator/.github/workflows/ci.yaml@main
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # uses sbt-github-packages, see build.sbt
      - run: bin/sbt publish
